### ISSUE TITLE
Documentation for fluid solvers?

### ISSUE THREAD

**Issue by alizma** [LLNL/echemfem#14]
The provided fluid solvers seem somewhat opaque and would benefit from further discussion. What are the permissible ranges of parameters? Maybe some references to how this works would also be helpful.

**Comment by tlroy** [comment]
Hi @alizma . I added some details to [the fluid solvers documentation](https://software.llnl.gov/echemfem/user_guide/fluid_solver.html), including a section at the end about the numerical method with references, and something about the range of parameters.

**Comment by alizma** [comment]
Looks good, thank you for the clarifications!
